   package net.oujda_nlp_team.util;
   
   public class ArabicCharacterUtil {
     public static String[] getSeparator() {
       String[] Str = { "\\.", "!", ":", "،", "؟", "؛" };
       return Str;
     }
     
     public static char getBuckWalterCharacter(char c) {
       switch (c) {
         case 'ء':
           return '\'';
         case 'آ':
           return '|';
         case 'أ':
           return '>';
         case 'ؤ':
           return '&';
         case 'إ':
           return '<';
         case 'ئ':
           return '}';
         case 'ا':
           return 'A';
         case 'ب':
           return 'b';
         case 'ة':
           return 'p';
         case 'ت':
           return 't';
         case 'ث':
           return 'v';
         case 'ج':
           return 'j';
         case 'ح':
           return 'H';
         case 'خ':
           return 'x';
         case 'د':
           return 'd';
         case 'ذ':
           return '*';
         case 'ر':
           return 'r';
         case 'ز':
           return 'z';
         case 'س':
           return 's';
         case 'ش':
           return '$';
         case 'ص':
           return 'S';
         case 'ض':
           return 'D';
         case 'ط':
           return 'T';
         case 'ظ':
           return 'Z';
         case 'ع':
           return 'E';
         case 'غ':
           return 'g';
         case 'ـ':
           return '_';
         case 'ف':
           return 'f';
         case 'ق':
           return 'q';
         case 'ك':
           return 'k';
         case 'ل':
           return 'l';
         case 'م':
           return 'm';
         case 'ن':
           return 'n';
         case 'ه':
           return 'h';
         case 'و':
           return 'w';
         case 'ى':
           return 'Y';
         case 'ي':
           return 'y';
         case 'ً':
           return 'F';
         case 'ٌ':
           return 'N';
         case 'ٍ':
           return 'K';
         case 'َ':
           return 'a';
         case 'ُ':
           return 'u';
         case 'ِ':
           return 'i';
         case 'ّ':
           return '~';
         case 'ْ':
           return 'o';
         case 'ٰ':
           return '`';
         case 'ٱ':
           return '{';
         case 'پ':
           return 'P';
         case 'چ':
           return 'J';
         case 'ڤ':
           return 'V';
         case 'گ':
           return 'G';
         case 'ژ':
           return 'R';
         case '،':
           return ',';
         case '؛':
           return ';';
         case '؟':
           return '?';
       } 
       return c;
     }
     
     public static char getArabicCharacter(char c) {
       switch (c) {
         case '\'':
           return 'ء';
         case '|':
           return 'آ';
         case '>':
           return 'أ';
         case '&':
           return 'ؤ';
         case '<':
           return 'إ';
         case '}':
           return 'ئ';
         case 'A':
           return 'ا';
         case 'b':
           return 'ب';
         case 'p':
           return 'ة';
         case 't':
           return 'ت';
         case 'v':
           return 'ث';
         case 'j':
           return 'ج';
         case 'H':
           return 'ح';
         case 'x':
           return 'خ';
         case 'd':
           return 'د';
         case '*':
           return 'ذ';
         case 'r':
           return 'ر';
         case 'z':
           return 'ز';
         case 's':
           return 'س';
         case '$':
           return 'ش';
         case 'S':
           return 'ص';
         case 'D':
           return 'ض';
         case 'T':
           return 'ط';
         case 'Z':
           return 'ظ';
         case 'E':
           return 'ع';
         case 'g':
           return 'غ';
         case '_':
           return 'ـ';
         case 'f':
           return 'ف';
         case 'q':
           return 'ق';
         case 'k':
           return 'ك';
         case 'l':
           return 'ل';
         case 'm':
           return 'م';
         case 'n':
           return 'ن';
         case 'h':
           return 'ه';
         case 'w':
           return 'و';
         case 'Y':
           return 'ى';
         case 'y':
           return 'ي';
         case 'F':
           return 'ً';
         case 'N':
           return 'ٌ';
         case 'K':
           return 'ٍ';
         case 'a':
           return 'َ';
         case 'u':
           return 'ُ';
         case 'i':
           return 'ِ';
         case '~':
           return 'ّ';
         case 'o':
           return 'ْ';
         case '`':
           return 'ٰ';
         case '{':
           return 'ٱ';
         case 'P':
           return 'پ';
         case 'J':
           return 'چ';
         case 'V':
           return 'ڤ';
         case 'G':
           return 'گ';
         case 'R':
           return 'ژ';
         case ',':
           return '،';
         case ';':
           return '؛';
         case '?':
           return '؟';
       } 
       return c;
     }
   }

