OPENAI_API_KEY = "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"
GOOGLE_API_KEY="AIzaSyDhCQunNxodVwoGCPhBeWaW1NzBZWCq7No"

[connections.postgresql]
dialect = "postgresql"
host = "127.0.0.1"
port = "5432"
database = "Quran_MetaData_Khair_v7_77444_tashkeel.postgres"
username = "postgres"
password = "Quran"

[connections.pgvector_google]
dialect = "postgresql"
host = "127.0.0.1"
port = "5432"
database = "pgvector_google"
username = "postgres"
password = "Quran"

[connections.pgvector_google_tashkeel]
dialect = "postgresql"
host = "127.0.0.1"
port = "5432"
database = "pgvector_google_tashkeel"
username = "postgres"
password = "Quran"

[google_credentials]
type= "service_account"
project_id= "poised-honor-367402"
private_key_id= "422e748ccd495069e0302e6cf5d2704121a28392"
private_key= "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDYRzPgbfcD5jtL\ns8GzXiYN88e1Y2tNlxMKPTk9ZH2WGfNyTPD9A7kCULPv33NdNueeWbIeVqkNk5JR\nTEBD6/f4U5vRawtBtaIxs0a5jpRZXvFTgePTFq3DOnXRPiPntbCrOhTHGUAVia49\n6eRN6l7xS0PcTVTYsX/cUMieROI/tWtboyQ7gKdb8mifYWzceMZ8uJgytEeSDV87\nO27+Azg2pRzWvwzC7ij3JCeSrlYHqDkcBWOIDou6Q29EOTxOYLtGmco4GJ2U0yTX\nhCFet8rIkax/8OTeZ1czm/fumwE6GzBlptxDBO7fDVGsNASyf78GqWATck8FYtBx\nCkhZaQCLAgMBAAECggEAHq0OuxztxdRQgb7H0Rif/iefImetDw7ICRJA/ae0tmcM\n5B/sqH5wLddjhjjj5ItGk+u1+16gUMgnHzfY/6lG/SZiufPcX2ATVshOVkBWY0y3\nnvgT59tWHxQ6JMkTD6jyG3879jdrIwLpv2de1fxRphjeUa94Qtn+QDIHGoe7rXxb\npg35jEHjQmLfhTCTwYdiELpiPC0q70HxmQCLbM6ADMww2iTBJQdwsJuLgIN/3KVW\n9ENFtr67Rhi51qPr6mOUD9K7A673YBWphUYn338M6PWZjbAVGB4DUz3Bfh0Rcuqh\nBxt2q6QaMhkxvM/T7S8mq9hGY1ndQftMkxVNy0ZQwQKBgQD0zoayKno/KCdV7INh\nKOMd5BTmVtCcY/Jpi/D+45Fa3PcGKtF5w93CfwPnxNXy0FTiS7fj+IEEba+xm2Px\nF9Tcr7whzhOQS4jGPuql1zGOQv/efLz5/57bKXc+sZyW78weYNGPS0AaS/1c1iPR\nO4+3nqyWz5Ygxw5gv0YtokmrywKBgQDiKr90B3vvNeyJdtAxyWSCryCeP6gKgzi/\nmOWL3jBZtrRH7ot7WGNtjz1QnaLWzGGhNfKIm3Oj4/5BIFm7rcEbJyebmLb1w/sp\nNg5KT5QbAUstcfc9Fgad6DYxAB1QR2o9hqFku289ahzyNLeY/cIxNlyJfgSe1QO2\n45p3iZTmQQKBgQDt+2+Z+A1LJF/I+dlmNHdFcZqXqUG3JrpbvL0VLGj7qd9CUZG+\nC5ijIRLM1t8d40UBkJY9ujDB+1dXEzZ/A6nct8HuIwWFushF4Jf/jEkSgTN4OE8F\nwWfOqmrPuZ3+ZTNLPNe7s22nosO04j+DgaFe4ZPqL/dD+f6SMp+ocSGpLQKBgQCW\nPQ1nN12Fv01813dfy0fAZDOHzAOF0DuPUzMRIaz+u5awve7cJhAOhHuXpM+6XpRw\nMdUGGDXOZjLM8n+JY9gGgJEYFG9dfS3H54fAp3JcKhTVgIJbitkkZlAxZsESRg52\nBowJzVUM+AN4hbp8n/0zEciQ8SyCkkBgant+8t79wQKBgA1n0TerRV1irIHKCPzQ\ntZEsM/AkivTFwphsjh7gBpCZVaQJtlfJporyb76BQAWf7YFUVQfZw+rTQgx8qw4J\nBjXgHeAWfB+eLV7FYCrXYzgMejRZRzIsZBdBKMaTw06luUlvHrYyIH4CLR8303jR\nWnQP+jZxTHSVBFR63ub1ufLg\n-----END PRIVATE KEY-----\n"
client_email= "google-service-khair@poised-honor-367402.iam.gserviceaccount.com"
client_id= "108575045941680094405"
auth_uri= "https://accounts.google.com/o/oauth2/auth"
token_uri= "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url= "https://www.googleapis.com/robot/v1/metadata/x509/google-service-khair%40poised-honor-367402.iam.gserviceaccount.com"
universe_domain= "googleapis.com"

